/*
 * Gurjit Singh
 * Tuesday December 3rd - 2019
 * This program displays the factorial, prime and fibonacci
 */

/**
 *
 * @author gusin5788
 */
public class factorialprimefibonaccifrm extends javax.swing.JFrame {

    /**
     * Creates new form factorialprimefibonaccifrm
     */
    public factorialprimefibonaccifrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        lblFirst = new javax.swing.JLabel();
        lblSecond = new javax.swing.JLabel();
        lblThird = new javax.swing.JLabel();
        lblFourth = new javax.swing.JLabel();
        lblFifth = new javax.swing.JLabel();
        lblSixth = new javax.swing.JLabel();
        lblSeventh = new javax.swing.JLabel();
        txtFirst = new javax.swing.JTextField();
        txtSecond = new javax.swing.JTextField();
        txtThird = new javax.swing.JTextField();
        btnFirst = new javax.swing.JButton();
        btnSecond = new javax.swing.JButton();
        btnThird = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFirst.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        lblFirst.setForeground(new java.awt.Color(0, 102, 0));
        lblFirst.setText("Factorial, Prime & Fibonacci");
        jPanel1.add(lblFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        lblSecond.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        lblSecond.setForeground(new java.awt.Color(0, 102, 0));
        lblSecond.setText("Enter a number and click the button to find the factorial:");
        jPanel1.add(lblSecond, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        lblThird.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        lblThird.setForeground(new java.awt.Color(0, 102, 0));
        lblThird.setText(".....");
        jPanel1.add(lblThird, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, -1, -1));

        lblFourth.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        lblFourth.setForeground(new java.awt.Color(0, 102, 0));
        lblFourth.setText("Enter a number and click the button to determine whether or not it is a prime number:");
        jPanel1.add(lblFourth, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        lblFifth.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        lblFifth.setForeground(new java.awt.Color(0, 102, 0));
        lblFifth.setText(".....");
        jPanel1.add(lblFifth, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, -1, -1));

        lblSixth.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        lblSixth.setForeground(new java.awt.Color(0, 102, 0));
        lblSixth.setText("Enter a number and click the button to see the corresponding Fibonacci number:");
        jPanel1.add(lblSixth, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        lblSeventh.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        lblSeventh.setForeground(new java.awt.Color(0, 102, 0));
        lblSeventh.setText(".....");
        jPanel1.add(lblSeventh, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, -1, -1));

        txtFirst.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        txtFirst.setForeground(new java.awt.Color(0, 102, 0));
        jPanel1.add(txtFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 70, -1));

        txtSecond.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        txtSecond.setForeground(new java.awt.Color(0, 102, 0));
        jPanel1.add(txtSecond, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 70, -1));

        txtThird.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        txtThird.setForeground(new java.awt.Color(0, 102, 0));
        jPanel1.add(txtThird, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 70, -1));

        btnFirst.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        btnFirst.setForeground(new java.awt.Color(0, 102, 0));
        btnFirst.setText("Factorial");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });
        jPanel1.add(btnFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));

        btnSecond.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        btnSecond.setForeground(new java.awt.Color(0, 102, 0));
        btnSecond.setText("Prime");
        btnSecond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSecondActionPerformed(evt);
            }
        });
        jPanel1.add(btnSecond, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, -1));

        btnThird.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        btnThird.setForeground(new java.awt.Color(0, 102, 0));
        btnThird.setText("Fibonacci");
        btnThird.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThirdActionPerformed(evt);
            }
        });
        jPanel1.add(btnThird, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        int number = Integer.parseInt(txtFirst.getText());
        int result = factorial(number);
        lblThird.setText(result + "");
    }
    public static int factorial(int number) {
        int result = 1;
        for (int i = 1; i <= number; i++) {
            result = result * i;
        }
        return result;
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnSecondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSecondActionPerformed
        int number = Integer.parseInt(txtSecond.getText());
        int temp;
        boolean isPrime = true;
        
        for (int i = 2; i <= number / 2; i = i + 1) {
            temp = number % i;
            
            if (temp == 0) {
                isPrime = false;
                break;
            }
        }
        if (isPrime) 
            lblFifth.setText(number + " is a prime number");
        else
            lblFifth.setText(number + " is not a prime number");
    }//GEN-LAST:event_btnSecondActionPerformed

    private void btnThirdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThirdActionPerformed
        int number = Integer.parseInt(txtThird.getText());
        int temp1 = 0, temp2 = 1;
        
        for (int i = 1; i <= number; i++)
        {
            lblSeventh.setText(temp1 + "");
            int sum = temp1 + temp2;
            temp1 = temp2;
            temp2 = sum;
        }    
    }//GEN-LAST:event_btnThirdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(factorialprimefibonaccifrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(factorialprimefibonaccifrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(factorialprimefibonaccifrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(factorialprimefibonaccifrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new factorialprimefibonaccifrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnSecond;
    private javax.swing.JButton btnThird;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel lblFifth;
    private javax.swing.JLabel lblFirst;
    private javax.swing.JLabel lblFourth;
    private javax.swing.JLabel lblSecond;
    private javax.swing.JLabel lblSeventh;
    private javax.swing.JLabel lblSixth;
    private javax.swing.JLabel lblThird;
    private javax.swing.JTextField txtFirst;
    private javax.swing.JTextField txtSecond;
    private javax.swing.JTextField txtThird;
    // End of variables declaration//GEN-END:variables
}
